In [3]:
# 1
arr_matrix = np.array([[1, 2, 3],[4, 5, 6]])
arr_transpose = np.transpose(arr_matrix)
print(arr_matrix)
print(arr_transpose)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [9]:
# 2
def assign_pets(lst):
    pets_dict = {}
    for tup in lst:
        owner = '{0} {1}'.format(tup[2], tup[3])
        pets = '{0}, возраст - {1}'.format(tup[0], tup[1])
        # pets_dict.setdefault(owner, list()).append(pets)
        if owner not in pets_dict:
            pets_dict.setdefault(owner, pets)
        else:
            pets_dict.update({owner: pets_dict.get(owner) + '; ' + pets})
    return pets_dict
lst = [('Муся', 7, 'Игорь', 'Бероев'), ('Изольда', 2, 'Игорь', 'Бероев')]
print(assign_pets(lst))

{'Игорь Бероев': 'Муся, возраст - 7; Изольда, возраст - 2'}


In [12]:
# 3
from collections import Counter
def rarest_word(string):
    if not string or string.isdigit():
        return 'Слов нет'
    new_string = ''
    for i in string:
        if i.isalpha() or i.isspace():
            new_string = new_string + i.lower()
    split_string = new_string.split()
    word_freqs = Counter(split_string)
    if not word_freqs: 
        return 'Слов нет'
    words = [i for i in word_freqs if word_freqs.get(i) == min(word_freqs.values())]
    return sorted(words)[0]
string = 'Дом, милый дом'
print(rarest_word(string))

милый


In [34]:
# 4
from collections import Counter
def most_frequent_word(string):
    if not string or string.isdigit():
        return 'Букв нет'
    new_string = ''.join(filter(str.isalpha, string.lower()))
    letters = Counter(new_string)
    if not letters:
        return 'Букв нет'
    max_value = max(letters.values())
    max_letters = [i for i in letters if letters[i] == max_value]
    return sorted(max_letters)[0]
string = 'Life is a nightmare that prevents one from sleeping'
print(most_frequent_word(string))

e


In [4]:
# 5
def palindrome(string):
    # убираем пробелы
    string = string.replace(' ', '')
    result = True
    if len(string) > 1:
        if string[0].lower() == string[-1].lower():
            result = palindrome(string[1:-1])
        else:
            result = False
    return result
string = 'аргентина манит негра'
print(palindrome(string))

True


In [38]:
# 6
from collections import Counter
def freq_sort(array): 
    nums = Counter(array)
    inverse_nums = {}
    for key, value in nums.items():
        inverse_nums.setdefault(value, list()).append(key)
    sorted_nums = dict(sorted(inverse_nums.items()))
    result = []
    for key, value in sorted_nums.items():
        for numbers in value:
            result.extend([numbers for i in range(key)])
    return result
array = ['арбуз', 'банан', 'Вишня', 'дыня', 'яблоко', 'арбуз']
print(freq_sort(array))

['банан', 'Вишня', 'дыня', 'яблоко', 'арбуз', 'арбуз']


In [16]:
# 7
def three_conseq_words(string):
    array = string.split()
    count = 0
    for i in range(len(array)):
        count += 1
        if not array[i].isalpha():
            count = 0
        if count == 3:
            return True
    return False
string = "Лето 24 празничные дни 333 я хочу спать 45"
print(three_conseq_words(string))

True


In [18]:
# 8
def max_consequence(string):
    string = string.lower()
    count = 1
    save = 0
    for i in range(len(string) - 1):
        if string[i] == string[i + 1] and string[i].isalpha():
            count += 1
            save = count if save < count else save
        else:
            count = 1
    return save
string = 'Цель искусства – раскрыть красоту и скрыть художника'
print(max_consequence(string))

2


In [3]:
# 9
"print(eval('1+(2+14)/(4-2)'))"
def math_expression(string):
    try:
        return eval(string)
    except Exception as e:
        return e
string = '1+(2+14)/(4-2)'
print(math_expression(string))

9.0


In [9]:
# 10
def summed_dict(list_of_dicts):
    new_dict = {}
    for dic in list_of_dicts:
        for key in dic.keys():
            if key not in new_dict.keys():
                new_dict.setdefault(key, dic.get(key))
            else:
                new_dict.update({key: new_dict.get(key) + dic.get(key)})
    return new_dict
list_of_dicts = [{'Пирожки': 185, 'Чебуреки': 5, 'Пельмени': 100, 'Хинкали': 35, 'Чебуреки': 362}]
print(summed_dict(list_of_dicts))

{'Пирожки': 185, 'Чебуреки': 362, 'Пельмени': 100, 'Хинкали': 35}
